# Generated by Django 6.0.1 on 2026-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='trailers/')),
                ('preview_image', models.ImageField(upload_to='previews/')),
                ('release_year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('age_rating', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
